### ISSUE TITLE
Drop Rusoto, adopt aws-sdk-rust?

### ISSUE THREAD

**Issue by brainstorm** [Fuuzetsu/zstd-seekable-s3#6]
Rusoto is pretty much dead at this point I reckon?

https://github.com/awslabs/aws-sdk-rust

**Comment by Fuuzetsu** [comment]
I think rusoto is "dead" as-in it has no _active_ maintenance or regular releases.

It's still in better state than the new official SDK:

```
Please Note: The SDK is currently released as an alpha and is intended strictly for feedback purposes only. Do not use this SDK for production workloads.
```

Most notably, it does not do basic things such as reading the credentials from all the right sources:

```
Note: The alpha SDK only supports environment variable credential providers at this time.
```

I am also excited about switching to the official SDK but it is just not usable yet in a library.

Let me know if you disagree with my judgement and I can re-open the ticket.

**Comment by brainstorm** [comment]
Very fair points indeed, used it myself without too much fuss though... worth re-visiting after ~6months?

Cheers!
