### ISSUE TITLE
rusoto 0.48 is out, just bumping the depdenencies seems to be enough to get the tests passing

### ISSUE THREAD

**Issue by pacak** [Fuuzetsu/zstd-seekable-s3#8]

**Comment by Fuuzetsu** [comment]
Do we care about updating rusoto at all? I think we'll just be switching to the official SDK at some point.

**Comment by pacak** [comment]
I think it deals with some duplicate dependencies plus it's noisy if we don't.

**Comment by Fuuzetsu** [comment]
It's 0.7.0 on crates.io
